services:
  laravel-app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./project:/var/www/project
  laravel-server:
    container_name: laravel-server
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app